spring:
  profiles:
    active: dev
  datasource:
    initialize: false

#mybatis:
#  mapperLocations: classpath:sqlmap/**/*.xml
#  typeAliasesPackage: com.ratel.info.api.model
app:
  tokenCode: 123456